services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cool
      POSTGRES_USER: cool
      POSTGRES_PASSWORD: coolpassword
    ports:
      - "5432:5432"
      # docker compose up --build
    volumes:
      - db_data:/var/lib/postgresql/data
      # data lives here

volumes:
  db_data: